import PhoneMockup from "@/components/PhoneMockup";
import type { Metadata } from "next";




export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <main >
            <div className="flex gap-5 p-5 /relative">
                <div className="hidden md:flex justify-center w-1/2 bg-white p-10 /fixed top-0"><PhoneMockup /></div>
                <div className=" w-full md:w-1/2">{children}</div>
            </div>
        </main>
    );
}
