import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ClientLayout from './ClientLayout'
import { Toaster } from 'react-hot-toast'
import { Footer } from '@/components'
const inter = Inter({ subsets: ['latin'] })
import Providers from './providers'

export const metadata: Metadata = {
  title: 'Dev Links',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
      <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" sizes="any"/>
      </head>
      <body className={inter.className}>
        <Toaster position='top-right' />
        {/* <Providers> */}
          <ClientLayout>
            {children}
            {/* <Footer/> */}
          </ClientLayout>
        {/* </Providers> */}
      </body>
    </html>
  )
}
