export {default as Footer} from "./Footer"
export {default as NavBar} from "./NavBar"
export {default as PreLoader} from "./PreLoader"
export {default as PhoneMockup} from "./phone-mockup/PhoneMockup"
export {default as NotFound} from "./NotFound"
